CREATE DATABASE todo_app DEFAULT CHARACTER SET utf8;

CREATE TABLE todo_app.todos (
    id INT AUTO_INCREMENT NOT NULL COMMENT 'ID',
    task_name VARCHAR(255) NOT NULL COMMENT 'タスク名',
    deadline DATE NOT NULL COMMENT '期限',
    status TINYINT(1) NOT NULL DEFAULT 0 COMMENT '状態 0: 未完了, 1: 完了',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'レコード作成日時',
    updated_at DATETIME DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT 'レコード更新日時',
    PRIMARY KEY (id)
);